kind: pipeline
name: default

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:7.0
    depends_on: [ clone ]
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - dotnet build JwtUtils/JwtUtils.csproj -c Release
      - dotnet test

  - name: push
    image: mcr.microsoft.com/dotnet/sdk:7.0
    environment:
      NUGET_APIKEY:
        from_secret: NUGET_APIKEY
    depends_on: [ build ]
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - dotnet pack JwtUtils/JwtUtils.csproj -c Release  /p:PackageVersion=$DRONE_TAG
      - dotnet nuget push **/JwtUtils.*.nupkg -k $NUGET_APIKEY -s https://www.nuget.org
    when:
      event:
        - tag

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock